development:
  adapter: postgresql
  encoding: unicode
  database: thames_commuter_development
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: thames_commuter_test
  host: localhost

